name: Enforce Codeowner

description: 'Enforce CODEOWNERS entries on PR files'

inputs:
  codeOwnersPath:
    description: 'Location of the codeowner file.'
    default: '.github/CODEOWNERS'
  commentPrefix:
    description: 'The message prefix to post on the PR.'
    default: 'The following files do not have code owners:'
  commentSuffix:
    description: 'The message suffix to post on the PR.'
    default: ''
  checkboxes:
    description: 'List the files with checkboxes.'
    default: false
  includeDeleted:
    description: 'Include deleted files.'
    default: false
  ignoredFiles:
    description: 'A new-line-separated list of ignored files.'
    default: ''
  token:
    description: 'The token used to authenticate with GitHub and post the comments on the PR.'
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}

outputs:
  comment:
    description: 'The output comment that should be posted on the pull request.'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'shield'
  color: 'gray-dark'
