name: Enforce Codeowner with Comment

description: 'Enforce CODEOWNERS entries on PR files'

inputs:
  codeOwnersPath:
    description: 'Location of the codeowner file.'
    default: '.github/CODEOWNERS'
  commentPrefix:
    description: 'The message prefix to post on the PR.'
    default: 'The following files do not have code owners:'
  commentSuffix:
    description: 'The message suffix to post on the PR.'
    default: ''
  checkboxes:
    description: 'List the files with checkboxes.'
    default: false
  custom-comment-identifier:
    description: 'A string that will be used to identify existing comments to update.'
    default: 'CODEOWNERS ACTION'
  token:
    description: 'The token used to authenticate with GitHub and post the comment on the PR.'
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}

runs:
  using: 'composite'
  steps:

    - name: Enforce Codeowners
      id: enforce-codeowners
      uses: worksome/enforce-codeowner@main
      with:
        codeOwnersPath: ${{ inputs.codeOwnersPath }}
        commentPrefix: |
          ${{ inputs.commentPrefix }}
        commentSuffix: |
          ${{ inputs.commentSuffix }}
        checkboxes: ${{ inputs.checkboxes }}
        token: ${{ inputs.token }}

    - name: Find Existing Comment
      uses: peter-evans/find-comment@v2
      id: find-comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body-includes: '<!-- ${{ inputs.custom-comment-identifier }} -->'
        token: ${{ inputs.token }}

    - name: Create comment
      if: ${{ steps.find-comment.outputs.comment-id == '' }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          <!-- ${{ inputs.custom-comment-identifier }} -->
          ${{ steps.enforce-codeowners.outputs.comment }}
        token: ${{ inputs.token }}

    - name: Update Comment
      if: ${{ steps.find-comment.outputs.comment-id != '' }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        edit-mode: replace
        body: |
          <!-- ${{ inputs.custom-comment-identifier }} -->
          ${{ steps.enforce-codeowners.outputs.comment }}
        token: ${{ inputs.token }}

branding:
  icon: 'shield'
  color: 'gray-dark'
